version: '3'

networks:
  webnet:
    driver: bridge

services:

  database:
    image: "postgres" # use latest official postgres version
    ports:
     - "5432:5432"
    networks:
     - webnet
    environment:
      - POSTGRES_USER=camunda
      - POSTGRES_PASSWORD=camunda
      - POSTGRES_DB=process-engine
    volumes:
      - ./target/database/:/var/lib/postgresql/data/
     
  camunda:
    image: camunda/camunda-bpm-platform:7.14.0
    restart: on-failure
    ports:
     - "80:8080"
    networks:
     - webnet
    depends_on:
     - "database"
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://database:5432/process-engine
      - DB_USERNAME=camunda
      - DB_PASSWORD=camunda
      - WAIT_FOR=database:5432
    links:
      - database
